/**
 * Mock database containing 10 luxury gift hamper products.
 * Priced in Indian Rupees (₹) with original, discounted, and percentage off values.
 */
export const mockProducts = [
  {
    id: 1,
    name: "Royal Chocolate Indulgence",
    category: "Chocolates & Sweets",
    shortDescription: "An exquisite collection of hand-crafted Belgian truffles and gold-foiled dark chocolates.",
    currentPrice: 1999,
    originalPrice: 2499,
    discountPercentage: 20,
    rating: 4.9,
    reviewCount: 124,
    stockStatus: "In Stock",
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1549007994-cb92ca813bec?auto=format&fit=crop&q=80&w=600"
  },
  {
    id: 2,
    name: "Premium Birthday Celebration Hamper",
    category: "Celebrations",
    shortDescription: "Make their special day unforgettable with premium treats, birthday sparkles, and customized decor.",
    currentPrice: 3499,
    originalPrice: 4999,
    discountPercentage: 30,
    rating: 4.8,
    reviewCount: 88,
    stockStatus: "In Stock",
    badge: "Trending",
    image: "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?auto=format&fit=crop&q=80&w=600"
  },
  {
    id: 3,
    name: "Executive Corporate Gift Box",
    category: "Corporate",
    shortDescription: "A sophisticated arrangement of premium leather accessories, fine writing tools, and select gourmet treats.",
    currentPrice: 4999,
    originalPrice: 5999,
    discountPercentage: 16,
    rating: 4.7,
    reviewCount: 54,
    stockStatus: "Limited Stock",
    badge: "Premium",
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=600"
  },
  {
    id: 4,
    name: "Wedding Elegance Basket",
    category: "Weddings",
    shortDescription: "Celebrate eternal love with premium champagne flutes, silk keepsakes, and delicate sweet delights.",
    currentPrice: 5999,
    originalPrice: 5999,
    discountPercentage: 0,
    rating: 5.0,
    reviewCount: 42,
    stockStatus: "In Stock",
    badge: "Luxury",
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=600"
  },
  {
    id: 5,
    name: "Luxury Dry Fruit Collection",
    category: "Gourmet Health",
    shortDescription: "An elegant wooden box filled with handpicked jumbo almonds, cashews, pistachios, and organic figs.",
    currentPrice: 1499,
    originalPrice: 1999,
    discountPercentage: 25,
    rating: 4.6,
    reviewCount: 146,
    stockStatus: "In Stock",
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&q=80&w=600"
  },
  {
    id: 6,
    name: "Premium Tea & Coffee Gift Box",
    category: "Beverages",
    shortDescription: "Indulge in artisanal organic leaf teas, single-origin coffee beans, and a hand-crafted ceramic mug.",
    currentPrice: 2499,
    originalPrice: 2999,
    discountPercentage: 16,
    rating: 4.8,
    reviewCount: 73,
    stockStatus: "Only 4 left",
    badge: "New Arrival",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600"
  },
  {
    id: 7,
    name: "Festive Celebration Hamper",
    category: "Festivals",
    shortDescription: "A joyous fusion of traditional sweets, scented candles, gold coins, and artisanal dry fruits.",
    currentPrice: 2999,
    originalPrice: 3999,
    discountPercentage: 25,
    rating: 4.9,
    reviewCount: 210,
    stockStatus: "In Stock",
    badge: "Festival Special",
    image: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&q=80&w=600"
  },
  {
    id: 8,
    name: "Personalized Luxury Gift Box",
    category: "Customized",
    shortDescription: "A tailor-made selection containing items personalized with your recipient's initials and favorite flavors.",
    currentPrice: 3499,
    originalPrice: 4999,
    discountPercentage: 30,
    rating: 4.9,
    reviewCount: 65,
    stockStatus: "In Stock",
    badge: "Luxury",
    image: "https://images.unsplash.com/photo-1581375221976-1f9e2b1029c3?auto=format&fit=crop&q=80&w=600"
  },
  {
    id: 9,
    name: "Gourmet Snack Collection",
    category: "Gourmet Health",
    shortDescription: "A delightful basket filled with organic cheese, cracker selections, artisan honey, and fresh spreads.",
    currentPrice: 1999,
    originalPrice: 2499,
    discountPercentage: 20,
    rating: 4.7,
    reviewCount: 95,
    stockStatus: "In Stock",
    badge: "Trending",
    image: "https://images.unsplash.com/photo-1534161309502-d39b8979e26b?auto=format&fit=crop&q=80&w=600"
  },
  {
    id: 10,
    name: "Luxury Spa & Wellness Hamper",
    category: "Spa & Wellness",
    shortDescription: "Create an oasis at home with premium lavender bath bombs, organic essential oils, and plush face towels.",
    currentPrice: 2999,
    originalPrice: 3999,
    discountPercentage: 25,
    rating: 4.9,
    reviewCount: 112,
    stockStatus: "In Stock",
    badge: "New Arrival",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=600"
  }
];
