spring.config.import=optional:file:.env[.properties]
# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations (Automatically update schema for new entities without dropping existing tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configurations (256-bit secure secret key)
hamperly.app.jwtSecret=${JWT_SECRET}
hamperly.app.jwtExpirationMs=${JWT_EXPIRATION_MS}

# Mail Server Configurations
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Application Reset Password URL
app.reset-password.url=http://localhost:5173/reset-password

